name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "11"
          - "12"
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "truffleruby+graalvm-head"
    name: macOS ${{ matrix.os }} - Ruby ${{ matrix.ruby }}
    runs-on: macos-${{ matrix.os }}
    env:
      TRUFFLERUBYOPT: "--jvm --polyglot"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install GraalVM JS component
        if: startsWith(matrix.ruby, 'truffleruby+graalvm')
        run: gu install js
      - name: Compile
        run: bundle exec rake compile
      - name: Test
        run: bundle exec rake test
